name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install UV required-version defined in pyproject.toml
      uses: astral-sh/setup-uv@v5
      with:
        pyproject-file: "./pyproject.toml"

    - name: Install dependencies
      run: |
        uv venv 
        uv pip install ".[dev]"

    - name: Run linters
      run: |
        ruff .
        mypy .

    - name: Test with pytest
      run: |
           uv run  pytest